services:
  backend:
    build:
      context: ./Backend
    container_name: crypto_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app

  frontend:
    build:
      context: ./Frontend
    container_name: crypto_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend
